// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function AddTask(Props) {
  return React.createElement("div", {
              className: "add-task-container"
            }, "react");
}

var make = AddTask;

export {
  make ,
}
/* react Not a pure module */
