// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as AddTask$MyResApp from "./AddTask.bs.js";
import * as TaskList$MyResApp from "./TaskList.bs.js";

import './styles/App.css';
;

function App(Props) {
  var match = React.useState(function () {
        return [
                "吃饭",
                "睡觉",
                "feeling life"
              ];
      });
  return React.createElement("div", {
              className: "container"
            }, React.createElement(AddTask$MyResApp.make, {}), React.createElement(TaskList$MyResApp.make, {
                  taskList: match[0]
                }));
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
