// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import './App.css';
;

function App(Props) {
  return React.createElement("div", {
              className: "container"
            });
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
