// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as TaskItem$MyResApp from "./TaskItem.bs.js";

function TaskList(Props) {
  var taskList = Props.taskList;
  return React.createElement("div", undefined, Belt_Array.map(taskList, (function (t) {
                    return React.createElement(TaskItem$MyResApp.make, {
                                taskName: t
                              });
                  })));
}

var make = TaskList;

export {
  make ,
}
/* react Not a pure module */
