// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function TaskItem(Props) {
  var taskName = Props.taskName;
  return React.createElement("div", undefined, taskName);
}

var make = TaskItem;

export {
  make ,
}
/* react Not a pure module */
